package tokens

import (
	"fmt"
	"log"
	"strings"

	"github.com/mcpchecker/mcpchecker/pkg/mcpproxy"
	"github.com/mcpchecker/mcpchecker/pkg/tokenizer"
)

type Source string

const (
	SourceEstimated Source = "estimated"
	SourceActual    Source = "actual"
)

type Usage struct {
	InputTokens       int64  `json:"inputTokens"`
	OutputTokens      int64  `json:"outputTokens"`
	TotalTokens       int64  `json:"totalTokens"`
	ThoughtTokens     *int64 `json:"thoughtTokens,omitempty"`
	CachedReadTokens  *int64 `json:"cachedReadTokens,omitempty"`
	CachedWriteTokens *int64 `json:"cachedWriteTokens,omitempty"`
}

// Estimate provides token count estimates for different components.
// Uses tiktoken library with cl100k_base encoding (may differ 10-30% for non-OpenAI models).
type Estimate struct {
	// InputTokens: tokens sent to the LLM (prompt + tool results + MCP schemas + resources + prompts)
	InputTokens int64 `json:"inputTokens"`
	// OutputTokens: tokens generated by the LLM (message + thinking + tool call params)
	OutputTokens int64 `json:"outputTokens"`
	// TotalTokens is InputTokens + OutputTokens
	TotalTokens int64 `json:"totalTokens"`

	// Agent breakdown
	// PromptTokens: the initial prompt sent to the agent
	PromptTokens int64 `json:"promptTokens"`
	// MessageTokens: agent's final response message
	MessageTokens int64 `json:"messageTokens"`
	// ThinkingTokens: agent's reasoning/thinking content
	ThinkingTokens int64 `json:"thinkingTokens"`

	// Tool call I/O
	// ToolInputTokens: tool call parameters (agent -> tools, counted as output)
	ToolInputTokens int64 `json:"toolInputTokens"`
	// ToolOutputTokens: tool results (tools -> agent, counted as input)
	ToolOutputTokens int64 `json:"toolOutputTokens"`

	// MCP server overhead
	// McpSchemaTokens: tool definitions (name+desc+inputSchema) + server instructions
	McpSchemaTokens int64 `json:"mcpSchemaTokens"`

	// Prompt get I/O
	// PromptGetInputTokens: prompt get arguments (agent -> MCP, counted as output)
	PromptGetInputTokens int64 `json:"promptGetInputTokens"`
	// PromptGetOutputTokens: prompt get results (MCP -> agent, counted as input)
	PromptGetOutputTokens int64 `json:"promptGetOutputTokens"`

	// Resource read I/O
	// ResourceInputTokens: resource read params (agent -> MCP, counted as output)
	ResourceInputTokens int64 `json:"resourceInputTokens"`
	// ResourceOutputTokens: resource read content (MCP -> agent, counted as input)
	ResourceOutputTokens int64 `json:"resourceOutputTokens"`

	// Error indicates if tokenization failed (partial or complete failure)
	Error string `json:"error,omitempty"`
	// Source indicates where the counts came from: "actual" or "estimated"
	Source Source `json:"source,omitempty"`
	// Actual contains real usage from agent when available (nil if only estimated)
	Actual *Usage `json:"actual,omitempty"`
}

// ToolCallData is a minimal struct to avoid circular dep
// TODO: see if we can remove this somehow
type ToolCallData struct {
	Name      string
	RawInput  any
	RawOutput any
}

func (u *Usage) Add(other *Usage) {
	if other == nil {
		return
	}

	u.InputTokens += other.InputTokens
	u.OutputTokens += other.OutputTokens
	u.TotalTokens += other.TotalTokens

	// take the only non nil field if one is set, else accumulate
	if u.ThoughtTokens == nil && other.ThoughtTokens != nil {
		v := *other.ThoughtTokens
		u.ThoughtTokens = &v
	} else if u.ThoughtTokens != nil && other.ThoughtTokens != nil {
		*u.ThoughtTokens += *other.ThoughtTokens
	}
	if u.CachedReadTokens == nil && other.CachedReadTokens != nil {
		v := *other.CachedReadTokens
		u.CachedReadTokens = &v
	} else if u.CachedReadTokens != nil && other.CachedReadTokens != nil {
		*u.CachedReadTokens += *other.CachedReadTokens
	}
	if u.CachedWriteTokens == nil && other.CachedWriteTokens != nil {
		v := *other.CachedWriteTokens
		u.CachedWriteTokens = &v
	} else if u.CachedWriteTokens != nil && other.CachedWriteTokens != nil {
		*u.CachedWriteTokens += *other.CachedWriteTokens
	}
}

// ComputeTokenEstimate calculates token estimates for agent execution.
// Populates breakdown fields only; callers should use RecalculateAggregates
// after any further merging (e.g., MCP call history) is complete.
func ComputeEstimate(prompt, message, thinking string, toolCalls []ToolCallData) Estimate {
	tok := tokenizer.Get()
	var errors []string

	promptTokens := countTextWithErrors(tok, prompt, "prompt", &errors)
	messageTokens := countTextWithErrors(tok, message, "message", &errors)
	thinkingTokens := countTextWithErrors(tok, thinking, "thinking", &errors)

	var toolInputTokens, toolOutputTokens int64
	for i, tc := range toolCalls {
		// Tool call parameters: agent -> tools (OUTPUT - agent generates these)
		// Skip nil values (e.g. ACP agent didn't send rawInput) to avoid
		// json.Marshal(nil) → "null" → 1 bogus token that would also prevent
		// MergeCallHistory from using the real MCP proxy counts.
		if tc.RawInput != nil {
			if count, err := tok.CountJSONTokens(tc.RawInput); err != nil {
				log.Printf("Warning: failed to count tool call input [%d] %q: %v", i, tc.Name, err)
				errors = append(errors, "tool_calls")
			} else {
				toolInputTokens += int64(count)
			}
		}
		// Tool results: tools -> agent (INPUT - these go back into agent context)
		if tc.RawOutput != nil {
			if count, err := tok.CountJSONTokens(tc.RawOutput); err != nil {
				log.Printf("Warning: failed to count tool result output [%d] %q: %v", i, tc.Name, err)
				errors = append(errors, "tool_results")
			} else {
				toolOutputTokens += int64(count)
			}
		}
	}

	var errorStr string
	if len(errors) > 0 {
		errorStr = fmt.Sprintf("failed to count: %s", strings.Join(errors, ", "))
	}

	return Estimate{
		PromptTokens:     promptTokens,
		MessageTokens:    messageTokens,
		ThinkingTokens:   thinkingTokens,
		ToolInputTokens:  toolInputTokens,
		ToolOutputTokens: toolOutputTokens,
		Error:            errorStr,
	}
}

// MergeCallHistory rolls up per-call token counts from MCP call history.
// Skips tool I/O if already populated (ACP mode) to avoid double-counting.
func (e *Estimate) MergeCallHistory(history *mcpproxy.CallHistory) {
	if history == nil {
		return
	}

	// For tool I/O: skip each field independently if already populated (ACP mode)
	var toolIn, toolOut int64
	for _, tc := range history.ToolCalls {
		if tc.Tokens != nil {
			toolIn += tc.Tokens.InputTokens
			toolOut += tc.Tokens.OutputTokens
		}
	}
	if e.ToolInputTokens == 0 {
		e.ToolInputTokens = toolIn
	}
	if e.ToolOutputTokens == 0 {
		e.ToolOutputTokens = toolOut
	}

	// Prompt and resource fields always come from CallHistory
	for _, pg := range history.PromptGets {
		if pg.Tokens != nil {
			e.PromptGetInputTokens += pg.Tokens.InputTokens
			e.PromptGetOutputTokens += pg.Tokens.OutputTokens
		}
	}
	for _, rr := range history.ResourceReads {
		if rr.Tokens != nil {
			e.ResourceInputTokens += rr.Tokens.InputTokens
			e.ResourceOutputTokens += rr.Tokens.OutputTokens
		}
	}
}

// RecalculateAggregates recomputes InputTokens, OutputTokens, TotalTokens
// from breakdown fields. No-op when Source is TokenSourceActual.
func (e *Estimate) RecalculateAggregates() {
	if e.Source == SourceActual {
		return
	}

	e.InputTokens = e.PromptTokens +
		e.ToolOutputTokens +
		e.McpSchemaTokens +
		e.ResourceOutputTokens +
		e.PromptGetOutputTokens
	e.OutputTokens = e.MessageTokens +
		e.ThinkingTokens +
		e.ToolInputTokens +
		e.ResourceInputTokens +
		e.PromptGetInputTokens
	e.TotalTokens = e.InputTokens + e.OutputTokens
}

// ToUsage returns the token counts as a Usage value.
// If actual usage is available, it is returned directly; otherwise a Usage
// is constructed from the aggregate estimate fields.
func (e *Estimate) ToUsage() *Usage {
	if e.Actual != nil {
		return e.Actual
	}
	return &Usage{
		InputTokens:  e.InputTokens,
		OutputTokens: e.OutputTokens,
		TotalTokens:  e.TotalTokens,
	}
}

// countTextWithErrors counts tokens in text, logging warnings and appending error labels on failure.
func countTextWithErrors(tok tokenizer.Tokenizer, text string, label string, errors *[]string) int64 {
	count, err := tok.CountTokens(text)
	if err != nil {
		log.Printf("Warning: failed to count tokens for %s: %v", label, err)
		*errors = append(*errors, label)
		return 0
	}
	return int64(count)
}
